[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    adafruit/Adafruit PN532

build_flags =
    -I include
    -I include/config
    -I hal
    -I hal/i2c
    -I hal/rtc_hal
    -I hal/uart
    -I drivers
    -I drivers/pn532
    -I drivers/ds3231
    -Idrivers/sim7600  
    -I services
    -I services/rfid_service
    -I services/time_service
    -I services/sim7600_service
    -I services/gps_service
    -I managers
    -I managers/authentication_manager
    -I app
    -I app/main

build_src_filter =
    +<../app/main/>
    +<../hal/i2c/>
    +<../hal/rtc_hal/>
    +<../hal/uart/>
    +<../drivers/pn532/>
    +<../drivers/ds3231/>
    +<../drivers/sim7600/>
    +<../services/rfid_service/>
    +<../services/time_service/>
    +<../services/sim7600_service/>
    +<../services/gps_service/>
    +<../managers/authentication_manager/>
    -<../test/>
    -<../tools/>
    -<../docs/>